language: node_js
node_js:
  - "node"
  - "lts/*"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
sudo: false
addons:
  code_climate:
    repo_token: c93da2cf072402fbbe53d73c3b136f50e3d337125b6f4b1c056881adab818d2e
script: "npm run coverage"
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
